package entity;
// Generated Nov 28, 2017 10:54:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Igrac generated by hbm2java
 */
@Entity
@Table(name="igrac"
    ,catalog="liverpoolfc"
)
public class Igrac  implements java.io.Serializable {


     private Integer igracId;
     private String ime;
     private String prezime;
     private String igracTekst;
     private String igracSlika;
     private String pozicija;
     private Integer brojDresa;

    public Igrac() {
    }

	
    public Igrac(String ime, String prezime, String igracTekst, String igracSlika, String pozicija) {
        this.ime = ime;
        this.prezime = prezime;
        this.igracTekst = igracTekst;
        this.igracSlika = igracSlika;
        this.pozicija = pozicija;
    }
    public Igrac(String ime, String prezime, String igracTekst, String igracSlika, String pozicija, Integer brojDresa) {
       this.ime = ime;
       this.prezime = prezime;
       this.igracTekst = igracTekst;
       this.igracSlika = igracSlika;
       this.pozicija = pozicija;
       this.brojDresa = brojDresa;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="igracId", unique=true, nullable=false)
    public Integer getIgracId() {
        return this.igracId;
    }
    
    public void setIgracId(Integer igracId) {
        this.igracId = igracId;
    }

    
    @Column(name="ime", nullable=false, length=45)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }

    
    @Column(name="prezime", nullable=false, length=45)
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    
    @Column(name="igracTekst", nullable=false, length=65535)
    public String getIgracTekst() {
        return this.igracTekst;
    }
    
    public void setIgracTekst(String igracTekst) {
        this.igracTekst = igracTekst;
    }

    
    @Column(name="igracSlika", nullable=false, length=45)
    public String getIgracSlika() {
        return this.igracSlika;
    }
    
    public void setIgracSlika(String igracSlika) {
        this.igracSlika = igracSlika;
    }

    
    @Column(name="pozicija", nullable=false, length=45)
    public String getPozicija() {
        return this.pozicija;
    }
    
    public void setPozicija(String pozicija) {
        this.pozicija = pozicija;
    }

    
    @Column(name="brojDresa")
    public Integer getBrojDresa() {
        return this.brojDresa;
    }
    
    public void setBrojDresa(Integer brojDresa) {
        this.brojDresa = brojDresa;
    }




}


