package entity;
// Generated Nov 28, 2017 10:54:11 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Korisnik generated by hbm2java
 */
@Entity
@Table(name="korisnik"
    ,catalog="liverpoolfc"
)
public class Korisnik  implements java.io.Serializable {


     private Integer korisnikId;
     private String ime;
     private String prezime;
     private String korisnickoIme;
     private String lozinka;
     private String email;
     private String korisnikSlika;
     private String tipKorisnika;
     private Set<Komentar> komentars = new HashSet<Komentar>(0);

    public Korisnik() {
    }

	
    public Korisnik(String ime, String prezime, String korisnickoIme, String lozinka, String email, String korisnikSlika, String tipKorisnika) {
        this.ime = ime;
        this.prezime = prezime;
        this.korisnickoIme = korisnickoIme;
        this.lozinka = lozinka;
        this.email = email;
        this.korisnikSlika = korisnikSlika;
        this.tipKorisnika = tipKorisnika;
    }
    public Korisnik(String ime, String prezime, String korisnickoIme, String lozinka, String email, String korisnikSlika, String tipKorisnika, Set<Komentar> komentars) {
       this.ime = ime;
       this.prezime = prezime;
       this.korisnickoIme = korisnickoIme;
       this.lozinka = lozinka;
       this.email = email;
       this.korisnikSlika = korisnikSlika;
       this.tipKorisnika = tipKorisnika;
       this.komentars = komentars;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="korisnikId", unique=true, nullable=false)
    public Integer getKorisnikId() {
        return this.korisnikId;
    }
    
    public void setKorisnikId(Integer korisnikId) {
        this.korisnikId = korisnikId;
    }

    
    @Column(name="ime", nullable=false, length=45)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }

    
    @Column(name="prezime", nullable=false, length=45)
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    
    @Column(name="korisnickoIme", nullable=false, length=45)
    public String getKorisnickoIme() {
        return this.korisnickoIme;
    }
    
    public void setKorisnickoIme(String korisnickoIme) {
        this.korisnickoIme = korisnickoIme;
    }

    
    @Column(name="lozinka", nullable=false, length=45)
    public String getLozinka() {
        return this.lozinka;
    }
    
    public void setLozinka(String lozinka) {
        this.lozinka = lozinka;
    }

    
    @Column(name="email", nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="korisnikSlika", nullable=false, length=45)
    public String getKorisnikSlika() {
        return this.korisnikSlika;
    }
    
    public void setKorisnikSlika(String korisnikSlika) {
        this.korisnikSlika = korisnikSlika;
    }

    
    @Column(name="tipKorisnika", nullable=false, length=45)
    public String getTipKorisnika() {
        return this.tipKorisnika;
    }
    
    public void setTipKorisnika(String tipKorisnika) {
        this.tipKorisnika = tipKorisnika;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="korisnik")
    public Set<Komentar> getKomentars() {
        return this.komentars;
    }
    
    public void setKomentars(Set<Komentar> komentars) {
        this.komentars = komentars;
    }




}


