package entity;
// Generated Nov 28, 2017 10:54:11 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Menadzer generated by hbm2java
 */
@Entity
@Table(name="menadzer"
    ,catalog="liverpoolfc"
)
public class Menadzer  implements java.io.Serializable {


     private Integer menadzerId;
     private String ime;
     private String prezime;
     private String menadzerTekst;
     private String tipMenadzera;
     private String menadzerSlika;

    public Menadzer() {
    }

    public Menadzer(String ime, String prezime, String menadzerTekst, String tipMenadzera, String menadzerSlika) {
       this.ime = ime;
       this.prezime = prezime;
       this.menadzerTekst = menadzerTekst;
       this.tipMenadzera = tipMenadzera;
       this.menadzerSlika = menadzerSlika;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="menadzerId", unique=true, nullable=false)
    public Integer getMenadzerId() {
        return this.menadzerId;
    }
    
    public void setMenadzerId(Integer menadzerId) {
        this.menadzerId = menadzerId;
    }

    
    @Column(name="ime", nullable=false, length=45)
    public String getIme() {
        return this.ime;
    }
    
    public void setIme(String ime) {
        this.ime = ime;
    }

    
    @Column(name="prezime", nullable=false, length=45)
    public String getPrezime() {
        return this.prezime;
    }
    
    public void setPrezime(String prezime) {
        this.prezime = prezime;
    }

    
    @Column(name="menadzerTekst", nullable=false, length=65535)
    public String getMenadzerTekst() {
        return this.menadzerTekst;
    }
    
    public void setMenadzerTekst(String menadzerTekst) {
        this.menadzerTekst = menadzerTekst;
    }

    
    @Column(name="tipMenadzera", nullable=false, length=45)
    public String getTipMenadzera() {
        return this.tipMenadzera;
    }
    
    public void setTipMenadzera(String tipMenadzera) {
        this.tipMenadzera = tipMenadzera;
    }

    
    @Column(name="menadzerSlika", nullable=false, length=45)
    public String getMenadzerSlika() {
        return this.menadzerSlika;
    }
    
    public void setMenadzerSlika(String menadzerSlika) {
        this.menadzerSlika = menadzerSlika;
    }




}


