package entity;
// Generated Nov 28, 2017 10:54:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Tekma generated by hbm2java
 */
@Entity
@Table(name="tekma"
    ,catalog="liverpoolfc"
)
public class Tekma  implements java.io.Serializable {


     private Integer tekmaRasporedId;
     private String protivnik;
     private Date vrijeme;
     private String stadion;
     private String domaciGosti;
     private String vrstaTakmicenja;
     private int goloviLiverpool;
     private int goloviProtivnik;

    public Tekma() {
    }

    public Tekma(String protivnik, Date vrijeme, String stadion, String domaciGosti, String vrstaTakmicenja, int goloviLiverpool, int goloviProtivnik) {
       this.protivnik = protivnik;
       this.vrijeme = vrijeme;
       this.stadion = stadion;
       this.domaciGosti = domaciGosti;
       this.vrstaTakmicenja = vrstaTakmicenja;
       this.goloviLiverpool = goloviLiverpool;
       this.goloviProtivnik = goloviProtivnik;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="tekmaRasporedId", unique=true, nullable=false)
    public Integer getTekmaRasporedId() {
        return this.tekmaRasporedId;
    }
    
    public void setTekmaRasporedId(Integer tekmaRasporedId) {
        this.tekmaRasporedId = tekmaRasporedId;
    }

    
    @Column(name="protivnik", nullable=false, length=45)
    public String getProtivnik() {
        return this.protivnik;
    }
    
    public void setProtivnik(String protivnik) {
        this.protivnik = protivnik;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="vrijeme", nullable=false, length=19)
    public Date getVrijeme() {
        return this.vrijeme;
    }
    
    public void setVrijeme(Date vrijeme) {
        this.vrijeme = vrijeme;
    }

    
    @Column(name="stadion", nullable=false, length=45)
    public String getStadion() {
        return this.stadion;
    }
    
    public void setStadion(String stadion) {
        this.stadion = stadion;
    }

    
    @Column(name="domaciGosti", nullable=false, length=45)
    public String getDomaciGosti() {
        return this.domaciGosti;
    }
    
    public void setDomaciGosti(String domaciGosti) {
        this.domaciGosti = domaciGosti;
    }

    
    @Column(name="vrstaTakmicenja", nullable=false, length=45)
    public String getVrstaTakmicenja() {
        return this.vrstaTakmicenja;
    }
    
    public void setVrstaTakmicenja(String vrstaTakmicenja) {
        this.vrstaTakmicenja = vrstaTakmicenja;
    }

    
    @Column(name="goloviLiverpool", nullable=false)
    public int getGoloviLiverpool() {
        return this.goloviLiverpool;
    }
    
    public void setGoloviLiverpool(int goloviLiverpool) {
        this.goloviLiverpool = goloviLiverpool;
    }

    
    @Column(name="goloviProtivnik", nullable=false)
    public int getGoloviProtivnik() {
        return this.goloviProtivnik;
    }
    
    public void setGoloviProtivnik(int goloviProtivnik) {
        this.goloviProtivnik = goloviProtivnik;
    }




}


