package entity;
// Generated Nov 28, 2017 10:54:11 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Vijest generated by hbm2java
 */
@Entity
@Table(name="vijest"
    ,catalog="liverpoolfc"
)
public class Vijest  implements java.io.Serializable {


     private Integer vijestId;
     private String naslov;
     private String tekst;
     private String vijestSlika;
     private Date vrijemeDatum;
     private Set<Komentar> komentars = new HashSet<Komentar>(0);

    public Vijest() {
    }

	
    public Vijest(String naslov, String tekst, String vijestSlika) {
        this.naslov = naslov;
        this.tekst = tekst;
        this.vijestSlika = vijestSlika;
    }
    public Vijest(String naslov, String tekst, String vijestSlika, Date vrijemeDatum, Set<Komentar> komentars) {
       this.naslov = naslov;
       this.tekst = tekst;
       this.vijestSlika = vijestSlika;
       this.vrijemeDatum = vrijemeDatum;
       this.komentars = komentars;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="vijestId", unique=true, nullable=false)
    public Integer getVijestId() {
        return this.vijestId;
    }
    
    public void setVijestId(Integer vijestId) {
        this.vijestId = vijestId;
    }

    
    @Column(name="naslov", nullable=false, length=200)
    public String getNaslov() {
        return this.naslov;
    }
    
    public void setNaslov(String naslov) {
        this.naslov = naslov;
    }

    
    @Column(name="tekst", nullable=false)
    public String getTekst() {
        return this.tekst;
    }
    
    public void setTekst(String tekst) {
        this.tekst = tekst;
    }

    
    @Column(name="vijestSlika", nullable=false, length=200)
    public String getVijestSlika() {
        return this.vijestSlika;
    }
    
    public void setVijestSlika(String vijestSlika) {
        this.vijestSlika = vijestSlika;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="vrijemeDatum", length=19)
    public Date getVrijemeDatum() {
        return this.vrijemeDatum;
    }
    
    public void setVrijemeDatum(Date vrijemeDatum) {
        this.vrijemeDatum = vrijemeDatum;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="vijest")
    public Set<Komentar> getKomentars() {
        return this.komentars;
    }
    
    public void setKomentars(Set<Komentar> komentars) {
        this.komentars = komentars;
    }




}


